### ISSUE TITLE
Intermittent Panic in SDK -- Possibly From AutoEvents

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/device-sdk-go#310]
I've been testing a lot of PRs over the last week using the device-random service. I've noticed that it crashes intermittently. Here's the scenario I go through. All of this is on the master branch.

- I fetch a local copy of the edgex-go PR and build it
- I then make sure I have the latest copy of device-random and pull in the latest device SDK if necessary
- I build device-random
- I clean out Mongo
- I start all of the edgex-go services
- I start device-random

I would say half the time, I get a panic like the one below. Then I start the device-random service again and it works fine. Notice the following at the top of the panic `fatal error: concurrent map writes`. So this sounds like a possible race condition. I suppose if that's true, it could happen while a service is running as well, but I've not seen that specific behavior.

From a cursory glance it looks like the problem is sourced in the goroutines started by [this function](https://github.com/edgexfoundry/device-sdk-go/blob/b6ad4c420792a66191cdf693bc4526796665caa8/internal/autoevent/manager.go#L58) that manage the [executor.lastReadings](https://github.com/edgexfoundry/device-sdk-go/blob/b6ad4c420792a66191cdf693bc4526796665caa8/internal/autoevent/executor.go#L27) map. And since it's a write, maybe the following operation isn't thread safe.

https://github.com/edgexfoundry/device-sdk-go/blob/b6ad4c420792a66191cdf693bc4526796665caa8/internal/autoevent/executor.go#L84

Full panic dump follows. It's very long.
```
Calling service.Start.
EnableRemote is true, using remote logging service
level=INFO ts=2019-06-13T22:35:16.58772Z app=device-random source=init.go:137 msg="Check Metadata service's status ..."
level=INFO ts=2019-06-13T22:35:16.587723Z app=device-random source=init.go:137 msg="Check Data service's status ..."
level=INFO ts=2019-06-13T22:35:16.593625Z app=device-random source=init.go:47 msg="Service clients initialize successful."
level=INFO ts=2019-06-13T22:35:16.595172Z app=device-random source=service.go:142 msg="Device Service  doesn't exist, creating a new one"
level=INFO ts=2019-06-13T22:35:16.596145Z app=device-random source=service.go:198 msg="Addressable device-random doesn't exist, creating a new one"
level=INFO ts=2019-06-13T22:35:16.615871Z app=device-random source=service.go:120 msg="*Service Start() called, name=device-random, version=1.0.0"
level=INFO ts=2019-06-13T22:35:16.615901Z app=device-random source=service.go:126 msg="Listening on port: 49988"
level=INFO ts=2019-06-13T22:35:16.615974Z app=device-random source=service.go:127 msg="Service started in: 30.644246ms"
fatal error: concurrent map writes

goroutine 113 [running]:
runtime.throw(0x1754ef4, 0x15)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000124d98 sp=0xc000124d68 pc=0x102bc22
runtime.mapassign_faststr(0x1660620, 0xc000315b30, 0xc00014e6e0, 0x1a, 0x1ce8460)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x42a fp=0xc000124e00 sp=0xc000124d98 pc=0x101270a
github.com/edgexfoundry/device-random/driver.(*RandomDriver).HandleReadCommands(0xc000104520, 0xc00014e6e0, 0x1a, 0xc000102f90, 0xc0003c8d00, 0x1, 0x1, 0xc0003030c0, 0x11, 0x0, ...)
	/Users/tconn/Documents/code/git/tsconn23/device-random/driver/randomdriver.go:42 +0x4ae fp=0xc000124ea8 sp=0xc000124e00 pc=0x14eb29e
github.com/edgexfoundry/device-sdk-go/internal/handler.execReadCmd(0xc000125a30, 0xc00014ec20, 0x19, 0x3, 0x19, 0x16b52fb1b01)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/handler/command.go:219 +0x55c fp=0xc0001254c8 sp=0xc000124ea8 pc=0x153681c
github.com/edgexfoundry/device-sdk-go/internal/handler.CommandHandler(0xc000213d88, 0x0, 0x0, 0x174a201, 0x3, 0x0, 0xc000314270, 0x203000)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/handler/command.go:79 +0x6b8 fp=0xc000125d38 sp=0xc0001254c8 pc=0x15345a8
github.com/edgexfoundry/device-sdk-go/internal/autoevent.readResource(0xc0000a8be0, 0xc000386870, 0x50, 0x0)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/autoevent/executor.go:78 +0x17a fp=0xc000125ed8 sp=0xc000125d38 pc=0x153bcda
github.com/edgexfoundry/device-sdk-go/internal/autoevent.(*executor).Run(0xc0000a8be0)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/autoevent/executor.go:41 +0x11a fp=0xc000125fd8 sp=0xc000125ed8 pc=0x153b67a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000125fe0 sp=0xc000125fd8 pc=0x1058671
created by github.com/edgexfoundry/device-sdk-go/internal/autoevent.triggerExecutors
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/autoevent/manager.go:68 +0x1af

goroutine 1 [chan receive]:
github.com/edgexfoundry/device-sdk-go/pkg/startup.startService(0x17505a3, 0xd, 0x183d398, 0x5, 0x185dd80, 0xc000104520, 0x2d, 0x100bcd8)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/pkg/startup/bootstrap.go:60 +0x1c9
github.com/edgexfoundry/device-sdk-go/pkg/startup.Bootstrap(0x17505a3, 0xd, 0x183d398, 0x5, 0x185dd80, 0xc000104520)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/pkg/startup/bootstrap.go:38 +0x38e
main.main()
	/Users/tconn/Documents/code/git/tsconn23/device-random/cmd/main.go:21 +0x74

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 5 [chan receive]:
github.com/edgexfoundry/device-sdk-go/pkg/startup.listenForInterrupt.func1(0xc000074300)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/pkg/startup/bootstrap.go:70 +0xe2
created by github.com/edgexfoundry/device-sdk-go/pkg/startup.listenForInterrupt
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/pkg/startup/bootstrap.go:67 +0x3f

goroutine 42 [IO wait]:
internal/poll.runtime_pollWait(0x4a51d08, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0000f6298, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000f6280, 0xc0002e2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1f2
net.(*netFD).Read(0xc0000f6280, 0xc0002e2000, 0x1000, 0x1000, 0xc0002ecea0, 0xc0002d4960, 0xc0001d5dd0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000092050, 0xc0002e2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
net/http.(*persistConn).Read(0xc00026e000, 0xc0002e2000, 0x1000, 0x1000, 0x1055e10, 0xc0001d5e88, 0x2)
	/usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc000094960)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc000094960, 0x1, 0x2, 0x0, 0x0, 0xc0002ece00, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc00026e000)
	/usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1357 +0xae8

goroutine 43 [select]:
net/http.(*persistConn).writeLoop(0xc00026e000)
	/usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1358 +0xb0d

goroutine 15 [chan receive]:
github.com/edgexfoundry/device-sdk-go.processAsyncResults()
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/async.go:26 +0xfa2
created by github.com/edgexfoundry/device-sdk-go.(*Service).Start
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/service.go:105 +0x7be

goroutine 54 [IO wait]:
internal/poll.runtime_pollWait(0x4a51a98, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000230198, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000230180, 0xc000318000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1f2
net.(*netFD).Read(0xc000230180, 0xc000318000, 0x1000, 0x1000, 0x1, 0x102da2c, 0xc0001d2b88)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00008c070, 0xc000318000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
net/http.(*persistConn).Read(0xc00026a120, 0xc000318000, 0x1000, 0x1000, 0xc0001d2c88, 0x1004ac5, 0xc0002da360)
	/usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc0001dc3c0)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc0001dc3c0, 0x1, 0x0, 0x0, 0x1, 0xc0002ecd00, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc00026a120)
	/usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1357 +0xae8

goroutine 55 [select]:
net/http.(*persistConn).writeLoop(0xc00026a120)
	/usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1358 +0xb0d

goroutine 78 [IO wait]:
internal/poll.runtime_pollWait(0x4a519c8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000328218, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000328200, 0xc000317000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1f2
net.(*netFD).Read(0xc000328200, 0xc000317000, 0x1000, 0x1000, 0xc0001663c0, 0xc000074d80, 0xc0002fbdd0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00032e040, 0xc000317000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
net/http.(*persistConn).Read(0xc000332000, 0xc000317000, 0x1000, 0x1000, 0x1055e10, 0xc0002fbe88, 0x2)
	/usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc000210f00)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc000210f00, 0x1, 0x2, 0x0, 0x0, 0xc000166300, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc000332000)
	/usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1357 +0xae8

goroutine 79 [select]:
net/http.(*persistConn).writeLoop(0xc000332000)
	/usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1358 +0xb0d

goroutine 13 [IO wait]:
internal/poll.runtime_pollWait(0x4a51b68, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000230518, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000230500, 0xc000376000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1f2
net.(*netFD).Read(0xc000230500, 0xc000376000, 0x1000, 0x1000, 0x1, 0x102da2c, 0xc0001d1b88)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0001ea158, 0xc000376000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
net/http.(*persistConn).Read(0xc000226240, 0xc000376000, 0x1000, 0x1000, 0xc0001d1c88, 0x1004ac5, 0xc0002da7e0)
	/usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc0000751a0)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc0000751a0, 0x1, 0x0, 0x0, 0x1, 0xc000076e00, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc000226240)
	/usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1357 +0xae8

goroutine 14 [select]:
net/http.(*persistConn).writeLoop(0xc000226240)
	/usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1358 +0xb0d

goroutine 16 [runnable]:
bytes.(*Buffer).Write(0xc0004840f0, 0xc000327474, 0x1, 0x1, 0x8, 0x15a7e2f4b9b5f308, 0xc0002d4d20)
	/usr/local/go/src/bytes/buffer.go:171 +0x116
encoding/binary.Write(0x184df40, 0xc0004840f0, 0x1868b20, 0x1ce75e8, 0x163ab80, 0x1c9011c, 0x16d9b60, 0xc0251ec301)
	/usr/local/go/src/encoding/binary/binary.go:342 +0x164
github.com/edgexfoundry/device-sdk-go/pkg/models.encodeValue(0xc0002d4d20, 0x163ab80, 0x1c9011c, 0x0, 0x0)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/pkg/models/commandvalue.go:251 +0x77
github.com/edgexfoundry/device-sdk-go/pkg/models.NewInt8Value(...)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/pkg/models/commandvalue.go:186
github.com/edgexfoundry/device-random/driver.(*RandomDriver).HandleReadCommands(0xc000104520, 0xc00014e6e0, 0x1a, 0xc000102f90, 0xc000330bc0, 0x1, 0x1, 0xc0001e87d0, 0x10, 0x0, ...)
	/Users/tconn/Documents/code/git/tsconn23/device-random/driver/randomdriver.go:57 +0x3be
github.com/edgexfoundry/device-sdk-go/internal/handler.execReadCmd(0xc0004b9a30, 0xc00014eae0, 0x18, 0x3, 0x18, 0x16b52fb1b01)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/handler/command.go:219 +0x55c
github.com/edgexfoundry/device-sdk-go/internal/handler.CommandHandler(0xc0002fdd88, 0x0, 0x0, 0x174a201, 0x3, 0x2, 0x2, 0x203000)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/handler/command.go:79 +0x6b8
github.com/edgexfoundry/device-sdk-go/internal/autoevent.readResource(0xc0000a8b90, 0xc000410aa0, 0x4f, 0x0)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/autoevent/executor.go:78 +0x17a
github.com/edgexfoundry/device-sdk-go/internal/autoevent.(*executor).Run(0xc0000a8b90)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/autoevent/executor.go:41 +0x11a
created by github.com/edgexfoundry/device-sdk-go/internal/autoevent.triggerExecutors
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/autoevent/manager.go:68 +0x1af

goroutine 114 [runnable]:
sync.(*Mutex).Unlock(0xc00000c060)
	/usr/local/go/src/sync/mutex.go:175 +0xd4
math/rand.(*lockedSource).seedPos(0xc00000c060, 0x15a7e2f4b9b62da0, 0xc0000781a8)
	/usr/local/go/src/math/rand/rand.go:404 +0x64
math/rand.(*Rand).Seed(0xc000078180, 0x15a7e2f4b9b62da0)
	/usr/local/go/src/math/rand/rand.go:76 +0x5a
math/rand.Seed(...)
	/usr/local/go/src/math/rand/rand.go:295
github.com/edgexfoundry/device-random/driver.random(0xffffffff80000000, 0x7fffffff, 0x6)
	/Users/tconn/Documents/code/git/tsconn23/device-random/driver/randomdevice.go:69 +0x8b
github.com/edgexfoundry/device-random/driver.(*randomDevice).value(0xc00032c270, 0x8, 0x1cc7a00, 0xc0002540f0, 0xc00034b338)
	/Users/tconn/Documents/code/git/tsconn23/device-random/driver/randomdevice.go:50 +0x490
github.com/edgexfoundry/device-random/driver.(*RandomDriver).HandleReadCommands(0xc000104520, 0xc00014e6e0, 0x1a, 0xc000102f90, 0xc00025a5a0, 0x1, 0x1, 0xc000303ca0, 0x11, 0x0, ...)
	/Users/tconn/Documents/code/git/tsconn23/device-random/driver/randomdriver.go:50 +0x177
github.com/edgexfoundry/device-sdk-go/internal/handler.execReadCmd(0xc0004b5a30, 0xc00014ed60, 0x19, 0x3, 0x19, 0x16b52fb1b01)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/handler/command.go:219 +0x55c
github.com/edgexfoundry/device-sdk-go/internal/handler.CommandHandler(0xc0001d0d88, 0x0, 0x0, 0x174a201, 0x3, 0x4a13eb0, 0xc0001d0da0, 0x100afd5)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/handler/command.go:79 +0x6b8
github.com/edgexfoundry/device-sdk-go/internal/autoevent.readResource(0xc0000a8c30, 0xc0004b0000, 0x50, 0x0)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/autoevent/executor.go:78 +0x17a
github.com/edgexfoundry/device-sdk-go/internal/autoevent.(*executor).Run(0xc0000a8c30)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/autoevent/executor.go:41 +0x11a
created by github.com/edgexfoundry/device-sdk-go/internal/autoevent.triggerExecutors
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/internal/autoevent/manager.go:68 +0x1af

goroutine 116 [IO wait]:
internal/poll.runtime_pollWait(0x4a518f8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0004a2018, 0x72, 0x0, 0x0, 0x174ba0d)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0004a2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc0004a2000, 0x16d1b20, 0x50, 0xc00049c050)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0004a6000, 0xc000055400, 0x1e09f80, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc0004a6000, 0x100bcd8, 0x30, 0x16d1b20)
	/usr/local/go/src/net/tcpsock.go:247 +0x48
net/http.tcpKeepAliveListener.Accept(0xc0004a6000, 0x16d1b20, 0xc000496150, 0x1669b80, 0x1cb7040)
	/usr/local/go/src/net/http/server.go:3264 +0x2f
net/http.(*Server).Serve(0xc0001f5d40, 0x185c880, 0xc0004a6000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2859 +0x22d
net/http.(*Server).ListenAndServe(0xc0001f5d40, 0xc0001f5d40, 0x1)
	/usr/local/go/src/net/http/server.go:2797 +0xe4
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3037
github.com/edgexfoundry/device-sdk-go.(*Service).Start.func1(0xc000074300, 0xc0001203c0, 0xc0000f20c0)
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/service.go:123 +0xe4
created by github.com/edgexfoundry/device-sdk-go.(*Service).Start
	/Users/tconn/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190606081229-b6ad4c420792/service.go:122 +0x59e
```

**Comment by cloudxxx8** [comment]
@tsconn23 thanks for reporting this issue.
After some investigation, it is caused by the non-thread-safe map in device-random.
https://github.com/edgexfoundry/device-random/blob/06d762cd8498261bf32027f3a07a143e9b025b88/driver/randomdriver.go#L23

However, you are right.  The lastReadings map in autoevent.executor is also non-thread-safe.
Thus, I will

1. move this issue to device-random
2. open another issue to fix the thread safe issue in autoevent.executor

**Comment by cloudxxx8** [comment]
Please see https://github.com/edgexfoundry/device-random/issues/66 and #311
