### ISSUE TITLE
Consul doesn't work when clients initial.

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/device-sdk-go#47]
Because client api use internal Consul variable. But when startup we have another Consul variable in sdk.

Error log:
```
Calling service.Start.
Init: useRegistry: true profile:  confDir: ./examples/simple/cmd/res/
Register in Consul...INFO: 2018/09/11 19:37:59 Check edgex-core-metadata service's status by Consul...
INFO: 2018/09/11 19:37:59 Check edgex-core-data service's status by Consul...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12979c3]

goroutine 85 [running]:
github.com/edgexfoundry/device-sdk-go/vendor/github.com/hashicorp/consul/api.(*Client).newRequest(0x0, 0x13e6c99, 0x3, 0x13ead4b, 0x12, 0x0)
	/Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/vendor/github.com/hashicorp/consul/api/api.go:644 +0x63
github.com/edgexfoundry/device-sdk-go/vendor/github.com/hashicorp/consul/api.(*Agent).Services(0xc000189d90, 0x0, 0x0, 0x0)
	/Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/vendor/github.com/hashicorp/consul/api/agent.go:245 +0x6d
github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/internal/pkg/consul.GetServiceEndpoint(0xc0000cc540, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/internal/pkg/consul/consul.go:85 +0x7b
github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/pkg/clients/types.Endpoint.Monitor(0xc0000cc540, 0x13, 0x13eb304, 0x13, 0x1, 0xc0001e80f0, 0x29, 0xc0001c82a0)
	/Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/pkg/clients/types/endpoint.go:15 +0x1c3
created by github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/pkg/clients/metadata.(*AddressableRestClient).init
	/Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/pkg/clients/metadata/addressable.go:54 +0xe6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12979c3]

goroutine 91 [running]:
github.com/edgexfoundry/device-sdk-go/vendor/github.com/hashicorp/consul/api.(*Client).newRequest(0x0, 0x13e6c99, 0x3, 0x13ead4b, 0x12, 0x0)
	/Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/vendor/github.com/hashicorp/consul/api/api.go:644 +0x63
github.com/edgexfoundry/device-sdk-go/vendor/github.com/hashicorp/consul/api.(*Agent).Services(0xc000185d90, 0x0, 0x0, 0x0)
	/Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/vendor/github.com/hashicorp/consul/api/agent.go:245 +0x6d
github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/internal/pkg/consul.GetServiceEndpoint(0xc0000cc540, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/internal/pkg/consul/consul.go:85 +0x7b
github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/pkg/clients/types.Endpoint.Monitor(0xc0000cc540, 0x13, 0x13ec1a6, 0x15, 0x1, 0xc0001e8180, 0x2b, 0xc0001c83c0)
	/Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/pkg/clients/types/endpoint.go:15 +0x1c3
created by github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/pkg/clients/metadata.(*DeviceProfileRestClient).init
	/Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/vendor/github.com/edgexfoundry/edgex-go/pkg/clients/metadata/device_profile.go:53 +0xe6

Process finished with exit code 2

```

**Comment by weichou1229** [comment]
I will work on this issue.
