### ISSUE TITLE
Example simple-device fails to run with confdir flag confict

### ISSUE THREAD

**Issue by mhall119** [edgexfoundry/device-sdk-go#52]
I built the example service and when trying to run it I get the following:
```
mhall@mhall-laptop:~/go/src/github.com/edgexfoundry/device-sdk-go/examples/simple/cmd$ ./simple-device 
./simple-device flag redefined: confdir
panic: ./simple-device flag redefined: confdir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc42007c060, 0x812e00, 0xc420080d70, 0x7ca8b7, 0x7, 0x7d9b25, 0x2d)
	/usr/lib/go-1.10/src/flag/flag.go:810 +0x540
flag.StringVar(0xc420080d70, 0x7ca8b7, 0x7, 0x0, 0x0, 0x7d9b25, 0x2d)
	/usr/lib/go-1.10/src/flag/flag.go:719 +0x8a
main.main()
	/home/mhall/go/src/github.com/edgexfoundry/device-sdk-go/examples/simple/cmd/main.go:40 +0x1ac
```

Changing the flag from "confdir" to "confDir" (or removing that flag altogether) fixes this issue.

**Comment by weichou1229** [comment]
@mhall119 I can't reproduce the issue. Below is my test steps.

* OS: macOS 10.13
* Go version : 1.11

Build and run.
```
Bruces-MBP:cmd bruce$ cd /Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/examples/simple/cmd
Bruces-MBP:cmd bruce$ go build -o simple-device
Bruces-MBP:cmd bruce$ ./simple-device 
Calling service.Start.
Init: useRegistry: false profile:  confDir: 
Bypassing registration in Consul...INFO: 2018/09/14 13:36:42 Check Metadata service's status ...
INFO: 2018/09/14 13:36:42 Check Data service's status ...
...
...
DEBUG: 2018/09/14 13:36:42 SimpleHandler.Initialize called!
DEBUG: 2018/09/14 13:36:42 initCommand called
INFO: 2018/09/14 13:36:42 *Service Start() called
ERROR: 2018/09/14 13:36:42 listen tcp :49990: bind: address already in use
DEBUG: 2018/09/14 13:36:42 *Service Start() exit
Setting up signals.
```
These steps work to me. It seems code is ok.

---
But if I add a code snippet  in man function. Then it can show similar error messages.
`flag.StringVar(&confDir, "confdir", "", "Specify an alternate configuration directory.")` 

```
func main() {
	var useRegistry bool
	var profile string
	var confDir string

	flag.BoolVar(&useRegistry, "registry", false, "Indicates the service should use the registry.")
	flag.BoolVar(&useRegistry, "r", false, "Indicates the service should use registry.")
	flag.StringVar(&profile, "profile", "", "Specify a profile other than default.")
	flag.StringVar(&profile, "p", "", "Specify a profile other than default.")
	flag.StringVar(&confDir, "confdir", "", "Specify an alternate configuration directory.")
	flag.StringVar(&confDir, "confdir", "", "Specify an alternate configuration directory.")
	flag.StringVar(&confDir, "c", "", "Specify an alternate configuration directory.")
	flag.Parse()

	if err := startService(useRegistry, profile, confDir); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}
```
and rebuild it.

```
Bruces-MBP:cmd bruce$ go build -o simple-device
Bruces-MBP:cmd bruce$ ./simple-device 
./simple-device flag redefined: confdir
panic: ./simple-device flag redefined: confdir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000082180, 0x1453260, 0xc000010f70, 0x13e9949, 0x7, 0x13f8c8f, 0x2d)
        /usr/local/go/src/flag/flag.go:805 +0x529
flag.StringVar(0xc000010f70, 0x13e9949, 0x7, 0x0, 0x0, 0x13f8c8f, 0x2d)
        /usr/local/go/src/flag/flag.go:714 +0x89
main.main()
        /Users/bruce/go/src/github.com/edgexfoundry/device-sdk-go/examples/simple/cmd/main.go:41 +0x1ec

```

**Comment by mhall119** [comment]
I used `make prepare` and `make build` from within the main device-sdk-go directory, can you see if you can reproduce it with that?

**Comment by cloudxxx8** [comment]
@mhall119 we fixed this issue with https://github.com/edgexfoundry/device-sdk-go/pull/59
please make a try.  Thanks

**Comment by mhall119** [comment]
Glad to know I wasn't going crazy, thanks @weichou1229 and @cloudxxx8!
